# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

# Performs requirements tracing using OpenFastTrace (https://github.com/itsallcode/openfasttrace)
# Uploads tracing report, returns the corresponding download URL as an output

name: Requirements tracing

on:
  workflow_call:
    inputs:
      oft-file-patterns:
        description: |
          A whitespace separated list of glob patterns which specify the files to include in the OFT trace run.
          If not specified, defaults to all files relevant for checking up-rust against the uProtocol Specification.
        type: string
        required: false
        default: "."
      oft-tags:
        description: |
          A comma separated list of tags to use for filtering specification items.
          If not set explicitly, all specification items from files matching the file patterns are considered.
        type: string
        required: false
        default: ""
      env-file-suffix:
        description: |
          Instead of explicitly specifying the file patterns and tags to use for the OpenFastTrace run, these
          values can also be read from a file in the workspace root folder. The file's name must start with
          `.env.` and end with this parameter's value. For example, if this parameter has value `oft-latest`,
          then the file being read will be `.env.oft-latest`.

          If this parameter is set to a non-empty value but the corresponding file does not exist, execution of the
          workflow will fail. Otherwise, the following variables are read from the file and will override any values specified explicitly using the corresponding input parameters:

          * `OFT_FILE_PATTERNS`
          * `OFT_TAGS`

          The variable values may refer to other variables defined in the file:
          
          ```sh
          OTHER_VARIABLE="*.yaml"
          OFT_FILE_PATTERNS="$OTHER_VARIABLE *.md"
          OFT_TAGS="_,SomeTag"
          ```
        type: string
        required: false
        default: ""
    outputs:
      tracing-report-url:
        description: "URL of the requirements tracing report"
        value: ${{ jobs.tracing.outputs.tracing-report-url }}

jobs:
  tracing:
    name: Run OpenFastTrace
    runs-on: ubuntu-latest
    outputs:
      tracing-report-url: ${{ steps.run-oft.outputs.tracing-report-url }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - run: |
          echo "OFT_FILE_PATTERNS=${{ inputs.oft-file-patterns }}" >> $GITHUB_ENV
          echo "OFT_TAGS=${{ inputs.oft-tags }}" >> $GITHUB_ENV

      - name: "Determine OpenFastTrace parameters from .env file"
        if: inputs.env-file-suffix != ''
        uses: xom9ikk/dotenv@v2.3.0
        with:
          mode: ${{ inputs.env-file-suffix }}
          load-mode: strict

      - name: Run OpenFastTrace
        id: run-oft
        uses: eclipse-uprotocol/ci-cd/.github/actions/run-oft@main
        with:
          file-patterns: ${{ env.OFT_FILE_PATTERNS }}
          tags: ${{ env.OFT_TAGS }}

      - name: "Determine exit code"
        run: |
          exit ${{ steps.run-oft.outputs.oft-exit-code }}
