# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

# Checks if the Minimum Supported Rust Version (MSRV) declared in a Rust project's
# Cargo.toml is correct, i.e. if the project can be compiled using a Rust toolchain
# of that version.

name: Check MSRV

on:
  workflow_call:

env:
  RUST_TOOLCHAIN: ${{ vars.RUST_TOOLCHAIN || 'stable' }}
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"
    - uses: dtolnay/rust-toolchain@master
      with: 
        toolchain: ${{ env.RUST_TOOLCHAIN }}
    - uses: taiki-e/install-action@cargo-hack
    - name: check MSRV
      run: |
        cargo hack check --rust-version --workspace --all-targets --all-features --ignore-private
