# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

# Run all test for all features to collect test code coverage information
# Upload coverage info for potential re-use in publication workflow, returns the corresponding download URL as an output on workflow_call
# Can publish coverage info to CodeCov platform, this is controlled by setting CODECOV_TOKEN secret in the github workspace

name: Test coverage

on:
  workflow_call:
    outputs:
      test_coverage_url:
        description: 'URL of the test coverage artifact'
        value: ${{ jobs.coverage.outputs.test_coverage_url }}
          
env:
  RUST_TOOLCHAIN: ${{ vars.RUST_TOOLCHAIN || 'stable' }}
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

permissions:
  contents: read # needed for checking out the code

jobs:
  coverage:
    name: Collect test coverage information
    runs-on: ubuntu-latest
    outputs:
      test_coverage_url: ${{ steps.test_coverage_html.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: "recursive"

      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with: 
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Install cargo-tarpaulin
        uses: taiki-e/install-action@25435dc8dd3baed7417e0c96d3fe89013a5b2e09 # v2.81.3
        with:
            tool: cargo-tarpaulin

      - name: Run tests and report code coverage
        run: |
          # enable nightly features so that we can also include Doctests
          RUSTC_BOOTSTRAP=1 cargo tarpaulin --workspace --implicit-test-threads --all-features --all-targets --doc -o xml -o lcov -o html

      - name: Upload coverage report (lcov)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: test_coverage_lcov
        with:
          name: code-coverage-lcov
          path: lcov.info
      - name: Upload coverage report (xml)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: test_coverage_xml
        with:
          name: code-coverage-xml
          path: cobertura.xml
      - name: Upload coverage report (html)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: test_coverage_html
        with:
          name: code-coverage-html
          path: tarpaulin-report.html

      - name: Upload coverage reports to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ vars.GITHUB_REPOSITORY }}
          files: lcov.info
